#!/usr/bin/python
# -*- coding:utf-8 -*-

import sys
import ccstuff

if __name__ == '__main__':
    argv = sys.argv
    i = ccstuff.rir()
    if len(argv) == 1:
        i.create_db()
    else:
        i.create_db(argv[1])
